### ISSUE TITLE
how to use isGranted method

### ISSUE THREAD

**Issue by furqanahmedpl** [ParkSangGwon/TedPermission#101]
hi,

i am using your library for getting run time permission from user

i have a case where i want to check wether user has already granted permission then do not use permission code 

i am trying to use isGranted(Context context, String... permissions): but no idea which class is giving this method.

can you please explain it more with 

any help would be highly appreciated

thanks

**Comment by ParkSangGwon** [comment]
You can use `TedPermission.isGranted()`
