### ISSUE TITLE
a little helping in READ.me

### ISSUE THREAD

**Issue by heywon0909** [ParkSangGwon/TedPermission#103]
안녕하세요! 저는 광운대학교 정보융합학부 학생 박혜원입니다.  저희 학교에서 오픈소스 기여라는 주제를 가지고 프로젝트를 진행 중인데요. 제가 관심있어하고 흥미로워하는 여러 GitHub안의 프로젝트를 보다가  님의 프로젝트를 보게 되었어요! 제가 코딩을 배운 지도 얼마 안됬고,  아직 2학년이라서 아직 많이 미흡하지만 님의 프로젝트를 찬찬히 읽어보며 공부를 해보고자 합니다! 저랑 같은 한국분이신데 영어 실력이 상당히 월등하셔서 너무 놀랐어요! 너무 멋지고 저도 훗날 그렇게 되고 싶어요! 
그런데 ,제가 READ.me 문서를 읽다가  무언가 수정하면 좋을 부분에 대해서 발견하게 되었어요.
READ.me 문서에서  How to use  부제목 아래  Normal 소제목아래 있는 문장 중에서 "you will 
get result to onPermissionGranted() or onPermissionDenied() depending on approved permissions"  get result를 get results 나 get a result 또는 get the result 라고 바꿔 표기하는 게 나을 듯 하다는 생각이 들었어요! 그런데 아무래도 특정 결과가 나왔다는 것을 나타내는 게 좋을 듯하여 get the result 나 get the results 이런 식으로 바꾸면 좋을 것 같아요!  
님의 프로젝트에  작지나만 의미있는 기여를 할 수 있으면 좋겠어요! 항상 행복한 하루 되시길
바랄께요~

**Comment by ParkSangGwon** [comment]
@heywon0909 
감사합니다.
오타정정이 필요한경우 수정된 Readme를 Pull request로 날려주시면 검토후 merge하도록 하겠습니다.
