### ISSUE TITLE
Is it possible dialog "accept" / "reject" button text color change?

### ISSUE THREAD

**Issue by loveprotocol** [ParkSangGwon/TedPermission#106]
Hello.
First of all, thank you for releasing a convenient library.
For custom, I want to change the color of the dialog button text. Is it possible?

**Comment by ParkSangGwon** [comment]
@loveprotocol 
If you mean this dialog, you can not change. 
Because this dialog is system dialog, not tedpermission's
![image](https://user-images.githubusercontent.com/8275048/65014773-8e591e80-d95a-11e9-8fef-a11f624bedf2.png)

**Comment by loveprotocol** [comment]
OK. Thanks for the quick response.
