### ISSUE TITLE
ERROR: Failed to resolve: gun0912.ted:tedpermission:x.y.z

### ISSUE THREAD

**Issue by iamsashank09** [ParkSangGwon/TedPermission#107]
I am unable to build the gradle, I am facing the error:

> ERROR: Failed to resolve: gun0912.ted:tedpermission:x.y.z
> Show in Project Structure dialog
> Affected Modules: app

Here is my app gradle. 

> apply plugin: 'com.android.application'
> 
> android {
>     compileSdkVersion 28
>     defaultConfig {
>         applicationId "com.enigmaticjunkies.apps.trafficsignhunter"
>         minSdkVersion 21
>         targetSdkVersion 28
>         versionCode 1
>         versionName "1.0"
>         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>     }
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>         }
>     }
> }
> 
> dependencies {
>     implementation fileTree(dir: 'libs', include: ['*.jar'])
>     implementation 'com.android.support:appcompat-v7:28.0.0-rc02'
>     implementation 'com.android.support.constraint:constraint-layout:1.1.3'
>     implementation 'gun0912.ted:tedpermission:x.y.z'
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'com.android.support.test:runner:1.0.2'
>     androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
>     implementation project(path: ':openCVLibrary341')
> }
> 
> repositories {
>     mavenCentral()
>     maven { url "https://jitpack.io" }
>     jcenter({url "http://jcenter.bintray.com/"})
> }

Please help me out with this.

Thanks a lot.

**Comment by FaisalFiyyaz** [comment]
@iamsashank09 change your library implementation to:
`implementation 'gun0912.ted:tedpermission:2.2.2'`
x.y.z is actually placeholder value and you have to replace it with library version

**Comment by iamsashank09** [comment]
> @iamsashank09 change your library implementation to:
> `implementation 'gun0912.ted:tedpermission:2.2.2'`
> x.y.z is actually placeholder value and you have to replace it with library version

Thank you. It is working. 

I tried it with 1.11.0 or something earlier and it did not work. So I thought it was some other issue.
