### ISSUE TITLE
Android 9, Galaxy S8 PermissionListener Runtime Exception

### ISSUE THREAD

**Issue by rlekqls12** [ParkSangGwon/TedPermission#112]
I am using version 2.2.3 and the requested permission is

Manifest.permission.ACCESS_FINE_LOCATION
Manifest.permission.WRITE_EXTERNAL_STORAGE          and

Starting with Version.M,
Manifest.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS

And I have runtime exceptions.

-----------------------------------------------------------------------------------
제가 사용하는 버전은 2.2.3이고, 갤럭시 S8 Android 9 버전에서 퍼미션 요청 후 Listener에서 받을 때
제일 처음에 Runtime Exception이 발생하고 튕깁니다. 그 이후에 다시 접속 하면 모든 권한을 허용해줬음에도 Listener에서 array가 null 값이라고 NullPointException이 뜹니다. 갤럭시 노트 10+ Android 10, Pixel2 Android 9, Nexus S Android 9에서는 정상 작동합니다.

**Comment by ParkSangGwon** [comment]
@rlekqls12 
`Manifest.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` is special permission.
You have to grant permission using other method
Check this link
https://developer.android.com/reference/android/provider/Settings#ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS

But I will support that permission using TedPermission
