### ISSUE TITLE
Not working when obfuscating

### ISSUE THREAD

**Issue by TurhanOz** [ParkSangGwon/TedPermission#12]
Have you tried your library with 'minify' enabled ?
It does not work : more precisely, the PermissionListener is never triggered.

The following proguard rule should fix it. Please update Readme accordingly : 
# TedPermission

-keep class com.gun0912.tedpermission.*\* {
  public protected private *;
}

Cheers

**Comment by TurhanOz** [comment]
a more fine tuned proguard rule should be found (as we have some insight regarding what is not working), but havn't had time to investigate more deeply.

**Comment by ParkSangGwon** [comment]
@TurhanOz 
Can't show permission dialog?
Or only doesn't PermissionListener trigger?

**Comment by TurhanOz** [comment]
It shows permission Dialog;
but PermissionListener not triggered indeed :/

**Comment by ecogeo** [comment]
Try this.

-keepattributes \*Annotation\*
-keepclassmembers class ** {
    @com.squareup.otto.Subscribe public *;
    @com.squareup.otto.Produce public *;
}

**Comment by TurhanOz** [comment]
It's very strange, I have new issues poping with obfuscation (with or without your any proguard rules stated above)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference
                                                       at com.gun0912.tedpermission.util.Dlog.buildLogMsg(Unknown Source)
                                                       at com.gun0912.tedpermission.util.Dlog.d(Unknown Source)
                                                       at com.gun0912.tedpermission.TedPermission.check(Unknown Source)

**Comment by TurhanOz** [comment]
`public static String buildLogMsg(String message) {
        StackTraceElement ste = Thread.currentThread().getStackTrace()[4];
        StringBuilder sb = new StringBuilder();
        sb.append("[");
        sb.append(ste.getFileName().replace(".java", ""));
        sb.append("::");
        sb.append(ste.getMethodName());
        sb.append("]");
        sb.append(message);
        return sb.toString();
    }

`

It seems that the StackTraceElement is null... (getting it from the 4th element of StackTrace leads to Null in this case...)
