### ISSUE TITLE
[docs] Adding some detailed explanations in README - "Setup" section?

### ISSUE THREAD

**Issue by FloweryK** [ParkSangGwon/TedPermission#138]
Hi,

First, Thank you for your great work.

As a newbie in android area, I was a little bit confused about README Setup section. I didn't realized that I should put the correct version (now it's 3.3.0) to x.y.z in `implementation 'io.github.ParkSangGwon:tedpermission-normal:x.y.z'`. Therefore I failed to build my project at first, but Eventually I found out how to fix it while googling 😄

So I suggest adding some detailed explanations in Setup section, like "put the corresponding version from the maven central button below into x.y.z in the line". 

I wonder if I can open a pull request about this.

Thank you.

<br/>

안녕하세요, 

먼저 좋은 라이브러리를 만들어주셔서 감사합니다.

이번에 처음 코틀린 프로젝트를 진행하면서 Ted Permission을 사용할 일이 생겼습니다. README를 보며 라이브러리를 적용하던 중, 제가 아직 초보여서 그런지 `implementation 'io.github.ParkSangGwon:tedpermission-normal:x.y.z'`에서 x.y.z의 의미를 몰라 빌드가 안돼서 약간 혼란이 있었습니다. (구글링해보고 해결하긴 했지만요 😄 )

그래서 그런데, 혹시 README의 Setup 부분에다가 "Maven Central 버튼 속에 표시된 버전을 x.y.z에 기입하세요" 같은 설명이 추가되면 어떨까요? 저같은 뉴비들은 이 정도의 설명만 추가되어도 설치에 혼란이 없을 것 같습니다.

괜찮다면 제가 풀리퀘를 열어도 되는지 알고싶습니다!

감사합니다.

**Comment by ted-prnd** [comment]
@FloweryK 
Yeah, that's good idea.
Of course, you can open pull request if you want.
