### ISSUE TITLE
Error gradle

### ISSUE THREAD

**Issue by minwonki** [ParkSangGwon/TedPermission#14]
I do not use your TedPermission

Error Message
Error:(25, 13) Failed to resolve: com.github.ParkSangGwon:TedPermission:v1.0.11
<a href="openFile:/Users/wkmin/Documents/AndroidStudioProjects/MyApplication/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

my gradle 
buildscript {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.smd.myapplication"
        minSdkVersion 18
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.github.ParkSangGwon:TedPermission:v1.0.11'
}

**Comment by ParkSangGwon** [comment]
@minwonki 
add    maven { url "https://jitpack.io" } in your app.gradle file

**Comment by minwonki** [comment]
It has been resolved.
thank you.

**Comment by Shakthi1109** [comment]
I already have marven. Still facing issue
