### ISSUE TITLE
missing POST_NOTIFICATION permission for Android 13

### ISSUE THREAD

**Issue by nishu3389** [ParkSangGwon/TedPermission#146]
Will you please provide an update with POST_NOTIFICATION permission introduced in Android 13,
Now it is mandatory to ask this runtime permission if we want to post notifications to the user

**Comment by devLaaziz** [comment]
+

**Comment by ParkSangGwon** [comment]
@nishu3389 @devLaaziz 
Have you checked the official documentation?
It doesn't matter if you request the permission or the POST_NOTIFICATION permission is added.
There is no problem requesting the POST_NOTIFICATION permission without adding the function in TedPermission separately.
