### ISSUE TITLE
EXTERNAL_STORAGE 권한 사용시

### ISSUE THREAD

**Issue by dyecolor** [ParkSangGwon/TedPermission#15]
Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE

2가지를 우선 넣고 테스트를 하고 있는데요. 다이얼로그 뜨는 순서가 이상합니다.
1. EXTERNAL_STORAGE 권한 요청 다이얼로그
2. RationaleMessage다이얼로그
3. EXTERNAL_STORAGE 권한 요청 다이얼로그

EXTERNAL_STORAGE 권한 요청 다이얼로그가 2번 뜨는 현상이 나오는데 혹시 저만 이런건가요?

**Comment by ParkSangGwon** [comment]
@dyecolor 좀더 자세한 로그나 소스코드를 볼수있을까요?
참고로 4.4 이상에서는 READ_EXTERNAL_STORAGE 권한없이 getExternalFilesDir(String), getExternalCacheDir() 함수를 이용가능합니다.

http://gun0912.tistory.com/55 블로그를 참고해주세요

**Comment by serendipper16** [comment]
저도 다이얼로그가 두번 뜨는 현상이 생겼는데 저의 경우에는 onResume()에서 권한체크를 해서 그랬었습니다. onCreate()에서 권한체크를 하니 정상적으로 한번만 실행되었습니다.
