### ISSUE TITLE
Blank Activity Animation shows my app_name

### ISSUE THREAD

**Issue by JoonyoungYi** [ParkSangGwon/TedPermission#16]
When I request permission with TedPermission, the dialog is showed in my activity. The dialog is showing from bottom to top... In this situation, @string/app_name is showed in the middle of the screen. So, I can see @string/app_name in a short time. It makes me feel somthing :( Can you remove the animation of the dialog or remove the text? Thanks! 

In Korean, 
권한을 요청하는 다이얼로그 창이 뜰때, 다이얼로그 창이 아래에서 위로 올라오는데요... 화면 중간에 app_name이 뜹니다. app_name이 그래서 잠깐 보이는데, 다소 신경쓰이네요 ㅠㅠㅠㅠ dialog창이 뜰 때 app_name이 뜨지 않게 바꿔주실 수 있을까요? 감사합니다.

**Comment by ecogeo** [comment]
저도 그런 증상이 있네요. 원래 안드로이드 문제인줄 알았는데 이게 이 라이브러리 문제인가요?

**Comment by JoonyoungYi** [comment]
@ecogeo 아 이게 안드로이드 문제인가요? ㅠㅠㅠㅠ 저는 안드로이드 문제일 것이라고 생각치 못했습니다 ㅠㅠㅠ dialog창 뜨는 화면전환 애니메이션을 꺼주시거나, text를 지워주시면 될 것이라 생각했는데.. 아닐 수도 있나보군요 ㅠㅠㅠㅠ

**Comment by lukasberant** [comment]
Hello,
I have same problem. When I request permission via TedPermission string app_name is displayed for a while in center of the screen. I dont want the app_name string to be visible. Is there any solution for that please?
