### ISSUE TITLE
trouble with android.permission.SYSTEM_ALERT_WINDOW

### ISSUE THREAD

**Issue by Yangxxxxx** [ParkSangGwon/TedPermission#19]
this code didn't work well with permisson "android.permission.SYSTEM_ALERT_WINDOW"

**Comment by ParkSangGwon** [comment]
@Yangxxxxx That function will be add

**Comment by ParkSangGwon** [comment]
@Yangxxxxx You can check `android.permission.SYSTEM_ALERT_WINDOW` at v1.0.2
