### ISSUE TITLE
난독화는 성공했는데 콜백을 불러오질 못합니다.

### ISSUE THREAD

**Issue by ehog0613** [ParkSangGwon/TedPermission#21]
proguard적용 난독화하여 apk파일까진 생성됐으나,
PermissionListener가 제대로 작동하지 않아 onPermissionGranted함수를 불러오질 못합니다.
마시멜로우 버전에서 그러네요. 

갓상권 블로그 정말 잘이용하고있고 많은 도움됐습니다.
응원합니다 화이팅!

**Comment by ParkSangGwon** [comment]
@ehog0613 otto의 영향일것으로 추측됩니다. 설명에 나와있는 Proguard설정 추가하셨나요?

**Comment by dkshin** [comment]
저도 같은 이슈입니다. 
proguard 설정 추가했는데 그렇네요

**Comment by ParkSangGwon** [comment]
이제 otto가 제거된 라이브러리로 변경되었습니다.
버전업을 하시고 Readme를 참고해주세요
```java
dependencies {
    compile 'gun0912.ted:tedpermission:2.0.0'
}
```
