### ISSUE TITLE
"ACCESS_FINE_LOCATION"  

### ISSUE THREAD

**Issue by ingu88** [ParkSangGwon/TedPermission#23]
ACCCESS_COARSE_LOCATION 는 잘되는데

ACCESS_FINE_LOCATION 이건 안되네요

블로그에는 Dangerous permissions 에 관해서 표가 있었는데

거기에 ACCESS_FINE_LOCATION 이것이 포함 되어있어서요.

넣고 돌렸을나 항상 DeniedMassage 만 출력 되는거 같네요.

구글에서 발표한 ACCESS_FINE_LOCATION 사용 변경에 대한 내용에 영향이 있는걸까요?

**Comment by ParkSangGwon** [comment]
Manifest에도 권한 선언을 해주셨나요?

**Comment by ParkSangGwon** [comment]
No answer close.
