### ISSUE TITLE
leakcanary : leaks DenyActivity instance

### ISSUE THREAD

**Issue by hoogeun** [ParkSangGwon/TedPermission#24]
메모리 사용량 증가 때문에 leakcanary로 메모리 누수 체크를 하는데  "leaks DenyActivity instance"
메세지가 떠네요, 아직 초보라 모르는게 많아서 한번 체크 부탁 드립니다.

**Comment by Wangjiaxing123** [comment]
It's dangerous that your TedPermission class has static TedInstance,it always leaks context!!!!!! 内存泄漏！这个是坑啊！

**Comment by ParkSangGwon** [comment]
@Wangjiaxing123 Do you use 1.0.3 version?
Current version fixed static instance issue.

**Comment by Wangjiaxing123** [comment]
ok,great!
