### ISSUE TITLE
Remove colorAccent from your library

### ISSUE THREAD

**Issue by isabsent** [ParkSangGwon/TedPermission#26]
Please, remove colorAccent parameter from your library. I have this parameter defined in my app and it conflicts with your definition!

    Error:(264, -1) Gradle: Attribute "colorAccent" has already been defined
Generally, it would be nice to remove all v7 dependencies. Instead of:

    import android.support.v7.app.AlertDialog;
    import android.support.v7.app.AppCompatActivity;
use

    import android.app.Activity;
    import android.app.AlertDialog;
/tedpermission/src/main/res/values/styles.xml change to one string:

    <style name="Theme.Transparent" parent="@android:style/Theme.NoTitleBar.Fullscreen"/>
And change /tedpermission/build.gradle from
    
    compile 'com.android.support:appcompat-v7:23.1.1'
to

    compile 'com.android.support:appcompat-v4:23+'

**Comment by ParkSangGwon** [comment]
@isabsent Tedpermission library don't have `colorAccent` attr.

**Comment by isabsent** [comment]
Tedpermission has colorAccent attr - it comes from 

    compile 'com.android.support:appcompat-v7:23.1.1'
dependecy in your build.gradle.

**Comment by ParkSangGwon** [comment]
If you want use your appcompat version, you can exclude library from tedpermission like this.
```java
compile('gun0912.ted:tedpermission:2.0.3') {
        exclude(module: 'appcompat-v7')
    }
```

**Comment by isabsent** [comment]
Unfortunately it does not work :( I have [forked your library](https://github.com/isabsent/TedPermission/tree/master) stripping `all support` dependencies. Min SDK level is 14. I generate `.aar` library from this fork and use it in my project.
