### ISSUE TITLE
Error:Plugin with id 'com.jfrog.bintray' not found.

### ISSUE THREAD

**Issue by isabsent** [ParkSangGwon/TedPermission#27]
Your project downloaded from github can not be compiled in WIndows 10 under Android Studio 2.2.2 and Intellij IDEA 2016.2.5 due to gradle error

    Error:Plugin with id 'com.jfrog.bintray' not found.

How to fix thi issue!?

**Comment by ParkSangGwon** [comment]
Did you still have problem?

**Comment by isabsent** [comment]
I didn't try it anymore.

**Comment by th-pias** [comment]
same problem. How can we solve this?

**Comment by ParkSangGwon** [comment]
@isabsent @th-pias 
Please pull repository.
I updated `build.gradle` file.
Then you can use sample project.

**Comment by crazycodepeng** [comment]
project  build.gradle  add
`dependencies {
        classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3"}`

**Comment by fukemy** [comment]
@crazycodepeng  not working for me

**Comment by jasanibhumi90** [comment]
@crazycodepeng not wokring for me

**Comment by sagarkhurana00786** [comment]
Now working can you help me
getting same error

**Comment by bhupalreddykokkanti007** [comment]
Not working. can you help me on it
