### ISSUE TITLE
Activity is closed but dialog permission is showed

### ISSUE THREAD

**Issue by amaydiam** [ParkSangGwon/TedPermission#29]
I call this fuction on created method, but Activity is closed but dialog permission is showed. Please fix it
`@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);
    
        new TedPermission(this)
                .setPermissionListener(permissionScanQrcodeListener)
                .setDeniedMessage("Permission dibutuhkan untuk Mode Offline.\nHidupkan permission WRITE_EXTERNAL_STORAGE pada [Setting] > [Permission]")
                .setPermissions(Manifest.permission.WRITE_EXTERNAL_STORAGE)
                .check();
    }`

**Comment by ParkSangGwon** [comment]
@amaydiam 
Did you mean activity was destroyed but dialog is still shown?
Request permission dialog is google's dialog. 
So I think we can not control that dialog.

**Comment by sion1116** [comment]
TedPermission를 사용하는 Activity의 android:noHistory="true"이면 
동일한 현상이 나타나더군요.
