### ISSUE TITLE
Unable to find explicit activity class com.gun0912.tedpermission.TedPermissionActivity

### ISSUE THREAD

**Issue by amaydiam** [ParkSangGwon/TedPermission#33]
Hello, I use this on my Apps, but i get error 
`
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.myapp.android/com.gun0912.tedpermission.TedPermissionActivity}; have you declared this activity in your AndroidManifest.xml`

I used any Library. This problem occurs when the added tools: node = "replace" on the manifest, but if it is removed, I get an error manifest merge failed

so how to fix it ?﻿

**Comment by ParkSangGwon** [comment]
@amaydiam If you use `tools:node="replace"`, library's manifest will be ignore.
I define `TedPermissionActivity` in library's manifest.
you can use `tools:node="merge”`
