### ISSUE TITLE
다이얼로그가 안뜨는문제.

### ISSUE THREAD

**Issue by rhkddn1657** [ParkSangGwon/TedPermission#34]
안드로이드 이제막 공부를 시작하는 초보생인데, 궁금증이 생겨서 여기에 질문을 드려도되는지 몰르겠지만. 혹시나해서 여쭈어봅니당..
new TedPermission(getActivity())
                .setPermissionListener(permissionlistener)
                .setRationaleMessage("이 기능을 사용하기 위해서는 단말기의 \"전화걸기 및 관리\" \" +\n" +
                        "//                                                \"권한이 필요합니다. 계속하시겠습니까?")
                .setDeniedMessage("앱 실행을 위해서는 전화 관리 권한을 \" +\n" +
                        "//                                                        \"설정해야 합니다\"")
                .setPermissions(Manifest.permission.READ_CONTACTS, Manifest.permission.CALL_PHONE)
                .check();

제가 이런식으로 설정하고 어플리케이션을 실행하면 권한설정을 하는 대화상자? 이게 떠야되는데 그게 안뜨고 바로 setRationaleMessage에 설정한 내용이 뜨는데 뭐가문제인건가요..?ㅠㅠ.

**Comment by ParkSangGwon** [comment]
@rhkddn1657 이전에 사용자가 권한요청에 대해서 거부를 하고 다시보지않기를 누른경우 권한요청 팝업은 뜨지않습니다.
앱을 삭제하고 다시 설치해보세요
