### ISSUE TITLE
Memory leak warning in Android Studio.

### ISSUE THREAD

**Issue by isabsent** [ParkSangGwon/TedPermission#36]
If you load your code in AS this warning appears:

    Do not place Android context classes in static fields (static reference to TedInstance which has field context pointing to Context); 
    this is a memory leak (and also breaks Instant Run).  A static field will leak contexts.
![ted_permission_memory_leak](https://cloud.githubusercontent.com/assets/4918293/22404303/87eed278-e660-11e6-9438-59e03907c328.png)

Is  there a way to avoid memory leaks using your library?

**Comment by ParkSangGwon** [comment]
@isabsent I removed static field `TedInstance`
You can user this code at v1.0.3
