### ISSUE TITLE
Soft Key board not open in Whole App

### ISSUE THREAD

**Issue by sohel274** [ParkSangGwon/TedPermission#40]
Sometime when we apply TedPermission in the application, soft keyboard not open. And When we comment the code of TedPermission, it's working fine. 

I use this library in my 4 application. Issue raise in 2 application another 2 application working properly.

I don't know why this issue occurs because of some permission issue ?

Please help.

@ParkSangGwon  can you please help...???

**Comment by ParkSangGwon** [comment]
Can you explain exactly?
What do you men 'soft keyboard not open' ?
Didn't show keyboard?

**Comment by sohel274** [comment]
On click or on focus of EditText not open the keyboard in whole App...

**Comment by ParkSangGwon** [comment]
I think that is not `Tedpermission`'s problem.
Can you show me video or screenshot?

**Comment by sohel274** [comment]
Yes I will

**Comment by ParkSangGwon** [comment]
No answer.
