### ISSUE TITLE
Open an activity after check permission is not available.

### ISSUE THREAD

**Issue by babogoos** [ParkSangGwon/TedPermission#41]
I'm trying to open an activity after permission check.
Here's how I code :
> 
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        PermissionListener permissionlistener = new PermissionListener() {
            @Override
            public void onPermissionGranted() {
                Toast.makeText(RationaleDenyActivity.this, "Permission Granted", Toast.LENGTH_SHORT).show();
            }
            @Override
            public void onPermissionDenied(ArrayList<String> deniedPermissions) {
                Toast.makeText(RationaleDenyActivity.this, "Permission Denied\n" + deniedPermissions.toString(), Toast.LENGTH_SHORT).show();
            }

        };
       new TedPermission(this)
                .setPermissionListener(permissionlistener)
                .setRationaleMessage("we need permission for read contact and find your location")
                .setDeniedMessage("If you reject permission,you can not use this service\n\nPlease turn on permissions at [Setting] > [Permission]")
                .setGotoSettingButtonText("bla bla")
                .setPermissions(Manifest.permission.READ_CONTACTS, Manifest.permission.ACCESS_FINE_LOCATION)
                .check();
        Intent intent=null;
        intent = new Intent(this,AfterCheckActivity.class);
        if(intent!=null){
            startActivity(intent);
        }
    }

This will make the permission dialog show up after AfterCheckActivity finish.
If I want to open an activity after check permission, where should I put the TedPermission.check() ?

**Comment by ParkSangGwon** [comment]
You have to write your code in `onPermissionGranted()` function.
Your code have to change like this.

```javascript
protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    PermissionListener permissionlistener = new PermissionListener() {
        @Override
        public void onPermissionGranted() {
            Toast.makeText(RationaleDenyActivity.this, "Permission Granted", Toast.LENGTH_SHORT).show();

  Intent intent=null;
    intent = new Intent(this,AfterCheckActivity.class);
    if(intent!=null){
        startActivity(intent);
    }

        }
        @Override
        public void onPermissionDenied(ArrayList<String> deniedPermissions) {
            Toast.makeText(RationaleDenyActivity.this, "Permission Denied\n" + deniedPermissions.toString(), Toast.LENGTH_SHORT).show();
        }


    };
   new TedPermission(this)
            .setPermissionListener(permissionlistener)
            .setRationaleMessage("we need permission for read contact and find your location")
            .setDeniedMessage("If you reject permission,you can not use this service\n\nPlease turn on permissions at [Setting] > [Permission]")
            .setGotoSettingButtonText("bla bla")
            .setPermissions(Manifest.permission.READ_CONTACTS, Manifest.permission.ACCESS_FINE_LOCATION)
            .check();
  
}
```
