### ISSUE TITLE
Unable to find explicit activity class

### ISSUE THREAD

**Issue by ntsparis** [ParkSangGwon/TedPermission#44]
Hello i have already read the previous issue nut i am consider if i am missing something. I use in manifest tools:node="replace" and when i change replace with merge i get this error :
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs.
Also i have multiDexEnabled true in grandle file.
Any idea?

**Comment by ParkSangGwon** [comment]
@ntsparis Why you use `tools:node`? Did you try remove that code?

**Comment by ParkSangGwon** [comment]
No answer. 
Close.
