### ISSUE TITLE
데모앱에 대한 질문..

### ISSUE THREAD

**Issue by shinshow** [ParkSangGwon/TedPermission#45]
데모앱을 갤럭시S6(Android 7.0)에 설치해서 실행해보던중 궁금한 점? 남깁니다.
앱 권한 거부후 나타나는 알림창에서 
'setting"버튼 클릭시
앱 권한 설정화면으로 넘어가는것이 아니라..
그냥
앱 정보화면으로 이동하는데 이게 맞는건가요?

**Comment by GodDM** [comment]
네 맞습니다

**Comment by ParkSangGwon** [comment]
맞습니다.
권한설정화면으로 가는 함수는 없습니다.
사용자가 직접 권한을 설정하려면 앱설정에서 권한을 들어간뒤에 권한을 on/off 해주어야 합니다.
