### ISSUE TITLE
targetSdkVersion 22인 경우에는?

### ISSUE THREAD

**Issue by shinshow** [ParkSangGwon/TedPermission#46]
우선 멋진 라이브러리 너무너무 감사드립니다....^^;
블로그에도 코멘트를 남기긴 했지만,,,,,

1) 앱이 설치된 기기는 마시멜로우 이상이고, 설치된 앱의 targetSdkVersion 22인 경우에는
TedPermission을 활용할 수 없는건가요?

기기의 OS버전이 마시멜로우 이상(또는 누가)인 경우에는 사용자가 언제나 앱 권한을 설정/해제할수 있기에
targetSdkVersion 22를 유지한체, 앱 권한 체크를 하고 싶은데 가능한건지 알고 싶습니다.

2) 이 라이브러리를 사용하기 위해서는 SYSTEM_ALERT_WINDOW 권한이 꼭 필요한건가요?

질문 게시판이 아님에도 질문만을 올려서 문제가 된다면 죄송합니다...

**Comment by GodDM** [comment]
1. API가 23에 추가된거라서 그 밑버젼은 TedPermission 뿐만아니라 checkSelfPermission(String)도 사용할수 없습니다.

2. 확실하진 않지만 SYSTEM_ALERT_WINDOW 권한은 라이브러리를 사용하기 위해 필요한 권한이 아니고 23부터 추가된 기능체크 중에 Settings.canDrawOverlays(context) 를 쓰고싶을때 권한 체크를 하기 위해 넣어 놓은거 같네요.

아니라면 테드님께 설명 부탁드립니다

**Comment by ParkSangGwon** [comment]
1. 22버전에서도 사용가능합니다.
하지만 targetSdkVersion에서는 동적권한 체크를 하실 필요가 없습니다.
무조건 권한획득상태로 들어옵니다.
동적권한체크는 23이상부터 체크해야하는 사항입니다.

2. SYSTEM_ALERT_WINDOW은 해당 권한을 사용할때 사용하면됩니다.
오버레이권한관련된 기능을 사용하지 않는다면 사용하실 필요 없습니다.

마시멜로 관련 내용은 아래 블로그를 참고하시기 바랍니다.
http://gun0912.tistory.com/55
