### ISSUE TITLE
Methods lose in v1.0.3

### ISSUE THREAD

**Issue by DanteAndroid** [ParkSangGwon/TedPermission#48]
![image](https://cloud.githubusercontent.com/assets/10005563/26094290/f2a207e0-3a4b-11e7-8eaf-136a70ab6b45.png)
So many methods lost in v1.0.3, please add them, thanks!
version: `  compile 'com.github.ParkSangGwon:TedPermission:v1.0.3' `

**Comment by ParkSangGwon** [comment]
@DanteAndroid Please check again. You can still use all method at v1.0.3
