### ISSUE TITLE
setDeniedMessage 작동 버그 같습니다.

### ISSUE THREAD

**Issue by leedabin** [ParkSangGwon/TedPermission#5]
new TedPermission(context).setDeniedMessage(getString(R.string.message))  이럴경우 정상적으로
다이어로그 메시지가 뜨는데

new TedPermission(context).setDeniedMessage(R.string.message) 이렇게 했을경우 다이어로그가 뜨지 않고 onPermissionDenied 으로 넘어가 버립니다. 그래서 권한 설정을 할수 없게 됩니다.

**Comment by ParkSangGwon** [comment]
@leedabin 
버그제보 감사합니다.
v1.0.8에서 수정되었습니다.
