### ISSUE TITLE
Should I show message dialog with Setting button every time app starts

### ISSUE THREAD

**Issue by AndrewGlukhoff** [ParkSangGwon/TedPermission#51]
Hi!
If the user has allowed any permissions that are very important to the app and denied other permissions which are not so important, with checking [x]Never ask again, then why should I show her message dialog with Setting button every time app starts ?

**Comment by ParkSangGwon** [comment]
@AndrewGlukhoff If you don't want show dialog, you can use `setGotoSettingButton(false)`
