### ISSUE TITLE
appcompat error 

### ISSUE THREAD

**Issue by BongJaeChoi** [ParkSangGwon/TedPermission#52]
version : 1.0.3

이슈 리스트에서 appcompat 관련 에러를 찾아보았습니다.

우선 저는 AppCompat 테마를 사용하고 있고 manifest에 application 의 theme 에 적용하고있습니다. 

하지만 여전히 테드 퍼미션을 사용시 
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity
와 같은 에러가 발생합니다.

**AndroidManifest.xml**
```
 <application
        android:name="com.xiilab.servicedev.cheesecounter.ApplicationClass"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:supportsRtl="true"
        android:theme="@style/AppTheme.NoActionBar">
...
```

**style.xml**
```
<style name="AppTheme" parent="Theme.AppCompat.Light">
        <!-- Customize your theme here. -->
        <item name="windowNoTitle">true</item>
        <item name="colorPrimary">@color/main_yellow</item>
        <item name="colorPrimaryDark">@color/main_yellow</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

    <style name="AppTheme.NoActionBar" parent="AppTheme">
        <item name="windowActionBar">true</item>
        <item name="windowNoTitle">true</item>
    </style>
```

**Comment by ParkSangGwon** [comment]
Dialog가 뜰때 Theme와 관련된 오류로 판단됩니다 확인후 수정해서 반영하겠습니다.

**Comment by hoya4206** [comment]
사용 중이신 style 중에 Theme.Transparent  이름으로 정의 된 style이 있나 찾아보세요~
그게 아마 라이브러랑 중복되서 기존 라이브러리의 리소스를 override 해버려서 생기는 문제 일 겁니다.

Please, check whether you have a style resource named "Theme.Transparent" or not.
If you have the style resource. Please change the name, so that not to be override this library's style resource.

상권님이 Style name을 좀더 유니크 한 것으로 바꿔주시면 좋겠네요~

**Comment by ParkSangGwon** [comment]
다이어로그가 실행될때 Theme를 지정해주었습니다.
버전업해서 오류가 발생하는지 확인해주세요
```java
dependencies {
    compile 'gun0912.ted:tedpermission:2.0.0'
}
```
