### ISSUE TITLE
denniedmessage always show

### ISSUE THREAD

**Issue by ivandiazmolina** [ParkSangGwon/TedPermission#53]
When I show the dialog, I click accept button and denied message show. How I can fix this?

I have try version 1.0.3 and 1.0.12 but I have got the same result

**Comment by ParkSangGwon** [comment]
@ivandiazmolina Can you show me your code?

**Comment by ivandiazmolina** [comment]
`new TedPermission(this.activity)
                .setPermissionListener(new PermissionListener() {
                    @Override
                    public void onPermissionGranted() {

                        activity.viewPager.setCurrentItem(4);
                        activity.viewPager.setAllowedSwipeDirection(CustomViewPager.SwipeDirection.none);

                    }

                    @Override
                    public void onPermissionDenied(ArrayList<String> deniedPermissions) {
                    }
                })
                .setDeniedMessage(getResources().getString(R.string.alert_permiso))
                .setPermissions(Manifest.permission.ACCESS_FINE_LOCATION)
                .check();`

**Comment by ParkSangGwon** [comment]
Hm... Can you upload your sample project?
