### ISSUE TITLE
onPermissionResult Null!!! How?

### ISSUE THREAD

**Issue by AnkurJagani** [ParkSangGwon/TedPermission#55]
`Caused by java.lang.RuntimeException: Could not dispatch event: class com.gun0912.tedpermission.busevent.TedPermissionEvent to handler [EventHandler public void com.gun0912.tedpermission.TedInstance.onPermissionResult(com.gun0912.tedpermission.busevent.TedPermissionEvent)]: null`

I have given all permissions and still it generating above exception on random times. Some times its working fine. Would you please help me in same context.

**Comment by AnkurJagani** [comment]
Hi,

Are you maintaining this library or not? Should we look for new library or close this thread?

Thanks.

**Comment by ParkSangGwon** [comment]
@AnkurJagani Do you use `Proguard`?

**Comment by AnkurJagani** [comment]
@ParkSangGwon Yes i am. Please check below configuration.
```
buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

proguard-rules.pro
```
-keep class org.apache.http.**{ *; }
-dontwarn org.apache.http.**
```
is there any problem in it?

**Comment by ParkSangGwon** [comment]
Please read this
https://github.com/ParkSangGwon/TedPermission#proguard

```javascript
-keepattributes *Annotation*
-keepclassmembers class ** {
    @com.squareup.otto.Subscribe public *;
    @com.squareup.otto.Produce public *;
}
```
