### ISSUE TITLE
setDeniedCloseButtonText(R.string.xxx or String) 

### ISSUE THREAD

**Issue by wallforfry** [ParkSangGwon/TedPermission#58]
Hi !

When I used setDeniedCloseButtonText(R.string.xxx or String) to change the "close" button's text, it's change the following text : "If you don't ....... [Settings] -> [Permission] " and not replace "close" by my string.

**Comment by ParkSangGwon** [comment]
Did you mean even you use `setDeniedCloseButtonText()`, Denied message changed?

**Comment by wallforfry** [comment]
Yes, exactly

**Comment by KKKimyh** [comment]
저도 같은 이슈입니다. setDeniedCloseButtonText 로 입력한 텍스트가 거부 팝업 문구에 표출됩니다.

**Comment by ParkSangGwon** [comment]
@KKKimyh @wallforfry 
This issue solved at #61 
You can use `2.0.4`version
