### ISSUE TITLE
Fragment error when initializing new TedPermission object

### ISSUE THREAD

**Issue by nicowxdvd** [ParkSangGwon/TedPermission#67]
I'm working on a fragment that requires the external card's permissions.

but when initializing the object

new TedPermission (ImagePickerFragment.this.getActivity ())
                

This does not recognize the activity, attached image with the message that appears, how can I solve it?

<img width="729" alt="captura de pantalla 2017-11-08 a la s 16 30 12" src="https://user-images.githubusercontent.com/4203771/32570209-3be8c6f6-c4a2-11e7-90ed-3253429a193b.png">

**Comment by ParkSangGwon** [comment]
In your fragment, you can use like this
```java
new TedPermission (getActivity())
```
or
```java
new TedPermission (getContext())
```

**Comment by nicowxdvd** [comment]
Already try that and doesnt work. I extend of baseFragment.  Any idea?

**Comment by ParkSangGwon** [comment]
@nicowxdvd 
Show me your full code.
Or upload your sample project here.

**Comment by nicowxdvd** [comment]
`
import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.app.Dialog;
import android.app.DialogFragment;
import android.content.DialogInterface;
import android.net.Uri;
import android.os.Bundle;
import android.support.v4.app.FragmentActivity;
import android.support.v7.widget.Toolbar;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.Toast;


import com.gun0912.tedpermission.PermissionListener;
import com.gun0912.tedpermission.TedPermission;

import java.util.ArrayList;

import au.com.carsales.R;
import au.com.carsales.international.BaseFragment;
import gun0912.tedbottompicker.TedBottomPicker;


public class ImagePickerFragment extends BaseFragment {
    private static final String TAG = CategoryPageFragment.class.getSimpleName();
    Toolbar toolbar;
    private FragmentActivity myContext;

    private ImageView imgPicker;
    private Button btnContinue;

    public static String getTAG() {
        return TAG;
    }

    public static ImagePickerFragment newInstance(Bundle arguments) {
        Bundle args = new Bundle();
        ImagePickerFragment fragment = new ImagePickerFragment();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public void onAttach(Activity activity) {
        myContext=(FragmentActivity) activity;
        super.onAttach(activity);
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view    =  inflater.inflate(R.layout.image_picker_fragment, container, false);

        toolbar         = (Toolbar) view.findViewById(R.id.toolbar);
        imgPicker       = (ImageView) view.findViewById(R.id.image_picker_btn) ;
        btnContinue     = (Button) view.findViewById(R.id.image_picker_btn_continue);
        toolbar.setTitle("Foto del vehículo");

        imgPicker.setOnClickListener(new View.OnClickListener(){
            public void onClick(View v) {
                showPicker();
            }
        });

        btnContinue.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                new FireMissilesDialogFragment().show(getActivity().getFragmentManager(), "MyDialog");
            }
        });


        return view;
    }

    public void showPicker(){
        PermissionListener permissionlistener = new PermissionListener() {
            @Override
            public void onPermissionGranted() {

                TedBottomPicker bottomSheetDialogFragment = new TedBottomPicker.Builder(ImagePickerFragment.this.getActivity())
                        .setOnMultiImageSelectedListener(new TedBottomPicker.OnMultiImageSelectedListener() {
                            @Override
                            public void onImagesSelected(ArrayList<Uri> uriList) {

                            }
                        })
                        //.setPeekHeight(getResources().getDisplayMetrics().heightPixels/2)
                        .setPeekHeight(1600)
                        .showTitle(false)
                        .setCompleteButtonText("Done")
                        .setEmptySelectionText("No Select")
                        //.setSelectedUriList(selectedUriList)
                        .create();

                bottomSheetDialogFragment.show(myContext.getSupportFragmentManager());


            }

            @Override
            public void onPermissionDenied(ArrayList<String> deniedPermissions) {
                Toast.makeText(ImagePickerFragment.this.getActivity(), "Permission Denied\n" + deniedPermissions.toString(), Toast.LENGTH_SHORT).show();
            }


        };


        new TedPermission (getActivity())
                .setPermissionListener(permissionlistener)
                .setDeniedMessage("If you reject permission,you can not use this service\n\nPlease turn on permissions at [Setting] > [Permission]")
                .setPermissions(Manifest.permission.WRITE_EXTERNAL_STORAGE)
                .check();



    }







    public static class FireMissilesDialogFragment extends DialogFragment {
        @Override
        public Dialog onCreateDialog(Bundle savedInstanceState) {
            // Use the Builder class for convenient dialog construction
            AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
            builder.setMessage("Hola, mundo!")
                    .setPositiveButton("ola k ase", new DialogInterface.OnClickListener() {
                        public void onClick(DialogInterface dialog, int id) {
                            // FIRE ZE MISSILES!
                        }
                    })
                    .setNegativeButton(R.string.cancel, new DialogInterface.OnClickListener() {
                        public void onClick(DialogInterface dialog, int id) {
                            // User cancelled the dialog
                        }
                    });
            // Create the AlertDialog object and return it
            return builder.create();
        }
    }



}
`
I also attach it to the user "getActivity()" and "getContext()"
<img width="1151" alt="captura de pantalla 2017-11-09 a la s 07 23 33" src="https://user-images.githubusercontent.com/4203771/32600700-375ccd9e-c51f-11e7-9041-4826cb7cd4d6.png">
<img width="1176" alt="captura de pantalla 2017-11-09 a la s 07 24 03" src="https://user-images.githubusercontent.com/4203771/32600701-3780bd94-c51f-11e7-9d47-b6bce1488268.png">

Regards

**Comment by nicowxdvd** [comment]
i already fixed, i use

TedPermission.with(this) instead of new TedPermission (getActivity()), Any idea why?
