### ISSUE TITLE
(RxJava) subscribe permission changed

### ISSUE THREAD

**Issue by susemi99** [ParkSangGwon/TedPermission#68]
혹시 RxJava의 `BehaviorSubject` 기능을 이용한 `권한 변경 상태 구독`이 가능할까요?
설정에서 권한을 끄고켰을 때, 앱에서 따로 권한 허용 여부를 물어보지 않아도 자동으로 권한이 있고없고를 알 수 있게 만들 수 있는지 궁금합니다.

**Comment by ParkSangGwon** [comment]
@susemi99 
권한이 필요한경우에 권한허용 여부를 체크하면 되지 않나요?
설정에서 권한을 끄고켰을때를 알아야할 경우는 어떤게 있나요?
참고로 설정에서 권한을 끄고켜면 Activity는 재시작됩니다.

**Comment by susemi99** [comment]
하는 김에 rx로 되면 좋을 것 같아서요...
찾아도 안 나오는 것 같아서 권한체크 하는 방식으로 쓰고 있습니다 ㅎㅎ
