### ISSUE TITLE
Rotational issue

### ISSUE THREAD

**Issue by Kito92** [ParkSangGwon/TedPermission#7]
Hi.
When the rotation is enabled and the dialog is showing, if I turn the device the method "onPermissionGranted" is called even if the user didn't make his decision.

**Comment by ParkSangGwon** [comment]
@Kito92 where did you check permission in your activity?

**Comment by Kito92** [comment]
@ParkSangGwon I call the check() method in the onResume() method of the fragment. I have to check the permission on the app's first opening. I put a log in the onPermissionGranted() method, and it's effectively called while screen is rotating! It works brilliantly, except for that issue.

**Comment by gogui63** [comment]
I've this issue too.

**Comment by ParkSangGwon** [comment]
I recommand check permission in `onCreate()`
why did you check permission in `onResume()`?

**Comment by gogui63** [comment]
I didn't check in OnResume,  I check in onCreate in my fragment

**Comment by Kito92** [comment]
Because I didn't see this part in the readme... Anyway if the user go to the setting to change the permissions and go back in the app the check won't be done because the onCreate isn't called unless the user kill the app and the fragment isn't create again! I guess this is the best way, and gogui63 already fix this!
