### ISSUE TITLE
Target SDK 26 에서 setDeniedMessage 팝업 시 죽는현상이 있습니다.

### ISSUE THREAD

**Issue by soonshinkwon** [ParkSangGwon/TedPermission#71]
안녕하세요 TedPermission Library 잘 사용중입니다.
Target SDK를 26으로 업데이트 하고 권한 설정창에서 죽는 문제가 있습니다.
권한 설정을 모두 [허용] 하면 문제가 없지만, [거부] 할 경우 마지막 denied 창 뜰때 죽습니다.
제 프로젝트의 환경과 로그를 첨부해 드립니다.

1. 프로젝트 개발환경
  Android Studio 3.0.1
  com.android.tools.build:gradle:3.0.1

  minSdkVersion 19  
  targetSdkVersion 26
  compileSdkVersion 26
  buildToolsVersion 26.0.3

  implementation ("com.android.support:appcompat-v7:26.1.0")
  implementation ("gun0912.ted:tedpermission:2.1.0")

2. 사용중인 코드 - 문제 발생
TedPermission.with(context)
  .setPermissionListener(listener)
  .setGotoSettingButton(true)
  .setDeniedMessage(message)
  .setPermissions(
    Manifest.permission.READ_EXTERNAL_STORAGE,
    Manifest.permission.WRITE_EXTERNAL_STORAGE,
    Manifest.permission.CAMERA,
    Manifest.permission.ACCESS_FINE_LOCATION,
    Manifest.permission.ACCESS_COARSE_LOCATION)
.check();

3. Denied 시 알림 팝업 설정을 주석처리 하면 문제 없습니다.
 아마 이 팝업에서 죽는듯 싶습니다.
TedPermission.with(context)
  .setPermissionListener(listener)
  .setGotoSettingButton(true)
  **//.setDeniedMessage(message)** 
  .setPermissions(
    Manifest.permission.READ_EXTERNAL_STORAGE,
    Manifest.permission.WRITE_EXTERNAL_STORAGE,
    Manifest.permission.CAMERA,
    Manifest.permission.ACCESS_FINE_LOCATION,
    Manifest.permission.ACCESS_COARSE_LOCATION)
.check();

4. 로그
12-11 21:09:37.227: E/AndroidRuntime(1584): java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.seers.thync.wearable.clip-I8AJNU2Wrj6xY5XO-6mSDw==/base.apk)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.widget.TintTypedArray.getFont(TintTypedArray.java:119)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.widget.AppCompatTextHelper.updateTypefaceAndStyle(AppCompatTextHelper.java:208)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:110)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:81)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1024)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1081)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:83)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.app.AlertController.installContent(AlertController.java:226)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:260)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:403)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.app.Dialog.show(Dialog.java:302)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.support.v7.app.AlertDialog$Builder.show(AlertDialog.java:958)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at com.gun0912.tedpermission.TedPermissionActivity.showPermissionDenyDialog(TedPermissionActivity.java:296)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at com.gun0912.tedpermission.TedPermissionActivity.onRequestPermissionsResult(TedPermissionActivity.java:257)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7388)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.app.Activity.dispatchActivityResult(Activity.java:7239)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.os.Looper.loop(Looper.java:164)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at java.lang.reflect.Method.invoke(Native Method)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
12-11 21:09:37.227: E/AndroidRuntime(1584): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
12-11 21:09:37.247: W/ActivityManager(796):   Force finishing activity com.seers.thync.wearable.clip/com.gun0912.tedpermission.TedPermissionActivity

**Comment by ParkSangGwon** [comment]
@soonshinkwon 
`buildToolsVersion`과 `com.android.support:appcompat`의 버전을 맞추고 테스트 해봐주시기 바랍니다.
샘플프로젝트에서는 문제 없습니다.

https://stackoverflow.com/questions/46945602/error-get-font-landroid-content-contextilandroid-util-typedvalue

**Comment by soonshinkwon** [comment]
네. sample 프로젝트에서는 당연히 문제가 없습니다.
제 프로젝트 환경이 샘플 프로젝트 보다 높은상황인데 이에 대한 대응 계획이 있으신지 궁금합니다.
