### ISSUE TITLE
Permission groups

### ISSUE THREAD

**Issue by xomnot** [ParkSangGwon/TedPermission#72]
Hi!

I implemented the library, and it is not asking for permission when permission group used:

`.setPermissions(Manifest.permission.READ_CONTACTS,
                        Manifest.permission_group.LOCATION,
                        Manifest.permission.WRITE_EXTERNAL_STORAGE,
                        Manifest.permission_group.PHONE,
                        Manifest.permission.SEND_SMS)`

This only asks fot contacts, external storage, and send sms.

**Comment by ParkSangGwon** [comment]
@xomnot 
Check dangerous permission
https://developer.android.com/guide/topics/security/permissions.html?hl=ko#normal-dangerous
You have to specific permission not permission group
