### ISSUE TITLE
PermissionListener callback method should implement List not ArrayList

### ISSUE THREAD

**Issue by bpappin** [ParkSangGwon/TedPermission#75]
The method `PermissionListener.onPermissionDenied(ArrayList<String> deniedPermissions) ` should be implemented as `PermissionListener.onPermissionDenied(List<String> deniedPermissions) `.

There is no need to be specific about the kind of list that will be returned.

**Comment by ParkSangGwon** [comment]
@bpappin Thanks. I will consider about it and fix it.
