### ISSUE TITLE
Grant all permition on one Go

### ISSUE THREAD

**Issue by NALAWALAMURTUZA** [ParkSangGwon/TedPermission#76]
My Client needs to grant all permissions in ONE GO. So is it possible if possible please Share code for that.

**Comment by ParkSangGwon** [comment]
@NALAWALAMURTUZA What do you mean all permissions
You can request all permissions at once.

**Comment by NALAWALAMURTUZA** [comment]
@ParkSangGwon Thank for reply.

in my application we asking all needed permissions (with alert). and one user accepts all **one by one** permission. then we will redirect to the login screen. 

so my client wants only one alert with all promotion. and if they click on **Grant all permissions** app will redirect to the login screen. not want multiple alerts to grant permission.
