### ISSUE TITLE
Release issue

### ISSUE THREAD

**Issue by KiminRyu** [ParkSangGwon/TedPermission#79]
#63 
위 이슈와 같은 문제를 겪고 있는데 ReadMe에 써있는 2.1.0 release에는 포함이 안되있는것 같습니다. ReadMe가 업데이트가 안된건가요, 아직 배포가 되지 않은건가요? Release tag는 v1에서 끊겨있네요 ㅠ

**Comment by JSpiner** [comment]
@KiminRyu 

[bintray](https://bintray.com/tkdrnjs0912/maven/tedpermission/2.1.0) 릴리즈 날짜를 보시면,  `2.1.0` 버전의 17년 11월 8일이고
해당 이슈는 18년 2월에 수정됬습니다. 
다음 릴리즈를 기다리시거나 현재 `master`브랜치를 받으셔서 사용하시면 될것 같습니다.

**Comment by dwkim-sugarhill** [comment]
@KiminRyu 
저도 이 상황에 대해 ted님에게 slack dm으로 문의를 드렸어요.
해외 일정과 개인적인 이슈로 확인을 못하셨다고 해요.
확인해보시고 답변 주신다고 하셨는데, 아직이네요~ 많이 바쁘신가봐요 ㅎㅎ

**Comment by ted-prnd** [comment]
@KiminRyu @JSpiner @dwkim-sugarhill 
#74 에서 해결된 버전 `2.1.1`버전으로 업데이트되었습니다.
바로 반영하지 못해서 죄송합니다.

**Comment by dwkim-sugarhill** [comment]
@ted-prnd @ParkSangGwon 감사합니다!!! 잘 사용 하겠습니다 ^^7
