### ISSUE TITLE
targetSdk 27 problem

### ISSUE THREAD

**Issue by KosilovAndrew** [ParkSangGwon/TedPermission#84]
Hello, I'm getting error after updating to targetSdk 27.
Could you help to fix it ?
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.grom.socialnetwork/com.gun0912.tedpermission.TedPermissionActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation

**Comment by ParkSangGwon** [comment]
@KosilovAndrew 
You can solve this issue at `2.1.1` version.
Thanks
