### ISSUE TITLE
Unable to Add in the Module

### ISSUE THREAD

**Issue by AnirudhLoya** [ParkSangGwon/TedPermission#9]
Where i need to add 

maven {
        url   "https://jitpack.io"
    }

i donot have project level build.gradle,so i want to add it in app module build.gradle 
![screen shot 2016-04-14 at 5 04 40 pm](https://cloud.githubusercontent.com/assets/5627238/14528098/74baf77e-026b-11e6-9fa2-87fb15a7c322.png)

**Comment by ParkSangGwon** [comment]
@AnirudhLoya how about v1.0.9 version?
did you add 
`maven { url "https://jitpack.io" }` in your build.gradle ?

**Comment by AnirudhLoya** [comment]
yes,i copy paste all class files and dependecies its working.

**Comment by gogui63** [comment]
@AnirudhLoya 
Add 
```
maven {
url "https://jitpack.io"
}
```
in build.gradle of your project not the buidl.gradle of your app : 
```
allprojects {
		repositories {
			...
			maven { url "https://jitpack.io" }
		}
	}
```

**Comment by AnirudhLoya** [comment]
i donot have project level build.gradle,i need to add it in app build.gradle because it is module we can say it library.

**Comment by gogui63** [comment]
You see : https://jitpack.io/docs/ANDROID/

**Comment by ParkSangGwon** [comment]
@AnirudhLoya https://jitpack.io/#ParkSangGwon/TedPermission/v1.0.9
