### ISSUE TITLE
Always showing the denial message

### ISSUE THREAD

**Issue by kingsammalik** [ParkSangGwon/TedPermission#90]
I implemented the library, i declined the permissions, then I went to the settings of the app and accepted the permissions, but after restarting app, again denial message is shown.

**Comment by ParkSangGwon** [comment]
@kingsammalik 
Can you show me video?
If permission granted, denial message can not shown.

**Comment by ParkSangGwon** [comment]
@kingsammalik 
I think you mistype permission name.
Or your library use same library like this.
```xml
<uses-permission
    android:name="android.permission.WRITE_EXTERNAL_STORAGE"
    android:maxSdkVersion="19" />
```
Then, permission dialog always show denied message.
Try this code in manifest.xml
```xml
<uses-permission
    android:name="android.permission.WRITE_EXTERNAL_STORAGE"
    tools:node="replace" />
```

**Comment by GrishinSergey** [comment]
@ParkSangGwon ,


> Or your library use same library like this.

Am I right, if suppose that this message possible, when I used this lib in my module (module1) and in main module (app)?
