### ISSUE TITLE
Convert Uri to Base64

### ISSUE THREAD

**Issue by nagaraj95** [ParkSangGwon/TedPermission#96]
How to convert selected multiple images into base 64 format?

**Comment by ParkSangGwon** [comment]
@nagaraj95 What do you mean?
This library about permission.

**Comment by nagaraj95** [comment]
Dear Sir,
  I send it wrongly.I need help from your multiple image picker.I want to
convert multiple images to base 64 format.

**Comment by ParkSangGwon** [comment]
Please ask to TedBottomPicker
